### ISSUE TITLE
Hosted Version - 502 Bad Gateway

### ISSUE THREAD

**Issue by JanLoebel** [opendata-stuttgart/metaEFA#11] opened 2017-07-15 14:14 UTC
Hi there,

just wanted to inform you about the broken "Hosted Version" of yours. 
Any access to https://efa-api.asw.io/ returns with "502 - Bad Gateway", so any project depending on your installation fails currently.

Best regards,
Jan

**Comment by mfa** [comment] 2017-07-15 17:20
duplicate of #10 
error is most likely on the vvs.de :(

**Closed by mfa** 2017-07-15 17:20 UTC
